import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#4F96BD',
  },
  flexbox1: {
    flex: 1,
    backgroundColor: 'white',
    //marginTop: 10,
    //borderTopLeftRadius: 30,
    //borderTopRightRadius: 30,
    marginVertical: '5%',
    borderRadius: 30,
    //paddingHorizontal: 10,
    //paddingVertical: 10,
  },
  image: {
    width: 130,
    height: 140,
    resizeMode: 'contain',
    //margin: 20,
  },
  flexbox2: {
    flex: 0.25,
    //backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  flexbox3: {
    flex: 0.1,
    //backgroundColor: 'gray',
    justifyContent: 'center',
    marginBottom: 20,
  },
  flexbox4: {
    flex: 0.12,
    //backgroundColor: 'yellow',
    justifyContent: 'center',
    marginBottom: 20,
  },
  flexbox5: {
    flex: 0.17,
    //backgroundColor: 'gray',
    justifyContent: 'center',
    marginBottom: 20,
  },
  text: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
  },
  bmitext: {
    fontSize: 30,
    borderWidth: 1,
    borderRadius: 10,
    marginLeft: 150,
    marginRight: 150,
    textAlign: 'center',
    color: 'black',
  },
  resulttext: {
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'black',
    borderWidth: 1,
    borderRadius: 10,
    marginLeft: 110,
    marginRight: 110,
  },
  text_footer: {
    color: '#05375a',
    fontSize: 18,
    marginLeft: 20,
    marginBottom: 10,
  },
  textInput: {
    flex: 1,
    //backgroundColor: 'yellow',
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    color: '#05375a',
  },
  flexbox6: {
    flex: 0.1,
    //backgroundColor: 'red',
    flexDirection: 'row',
    marginTop: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    paddingBottom: 5,
    marginLeft: 20,
    marginBottom: 20,
  },
  signIn: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'black',
    borderWidth: 1,
    marginTop: 15,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'lightblue',
  },
  signIn1: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'black',
    borderWidth: 1,
    marginTop: 15,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'white',
  },
  button: {
    alignItems: 'center',
    marginLeft: 30,
    marginRight: 30,
    marginBottom: 30,
  },
  textSign: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
  },

  centeredView: {
    justifyContent: 'center',
  },
  modalView: {
    margin: 20,
    backgroundColor: '#4F96BD',
    //backgroundColor: 'lightblue',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 20,
    color: 'black',
  },
  modaltextresult: {
    //marginBottom: 15,
    textAlign: 'center',
    fontSize: 25,
    color: 'white',
    margin: 10,
  },
  modalheading: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 25,
    color: 'white',
  },
  flexbox7: {
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 10,
    marginBottom: 15,
  },

  Landscapecontainer: {
    flex: 1,
    backgroundColor: '#4F96BD',
  },
  Landscapeflexbox1: {
    flex: 1,
    backgroundColor: 'white',
    marginHorizontal: '18%',
    //borderRadius: 30,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  Landscapeimage: {
    width: 130,
    height: 140,
    resizeMode: 'contain',
    //margin: 20,
  },
  Landscapeflexbox2: {
    flex: 0.25,
    //backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  Landscapeflexbox3: {
    flex: 0.1,
    //backgroundColor: 'gray',
    justifyContent: 'center',
    marginBottom: 20,
  },
  Landscapeflexbox4: {
    flex: 0.12,
    //backgroundColor: 'yellow',
    justifyContent: 'center',
    marginBottom: 20,
  },
  Landscapeflexbox5: {
    flex: 0.17,
    //backgroundColor: 'gray',
    justifyContent: 'center',
    marginBottom: 20,
    marginLeft: 30,
    marginRight: 30,
  },
  Landscapetext: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
  },
  Landscapebmitext: {
    fontSize: 30,
    borderWidth: 1,
    borderRadius: 10,
    marginLeft: 150,
    marginRight: 150,
    textAlign: 'center',
    color: 'black',
  },
  Landscaperesulttext: {
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'black',
    borderWidth: 1,
    borderRadius: 10,
    marginLeft: 110,
    marginRight: 110,
  },
  Landscapetext_footer: {
    color: '#05375a',
    fontSize: 18,
    marginLeft: 20,
    marginBottom: 10,
  },
  LandscapetextInput: {
    flex: 1,
    //backgroundColor: 'yellow',
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    color: '#05375a',
  },
  Landscapeflexbox6: {
    flex: 0.1,
    //backgroundColor: 'red',
    flexDirection: 'row',
    marginTop: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    paddingBottom: 5,
    marginLeft: 20,
    marginBottom: 20,
  },
  LandscapesignIn: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'black',
    borderWidth: 1,
    marginTop: 15,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'lightblue',
  },
  LandscapesignIn1: {
    width: '70%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'black',
    borderWidth: 1,
    marginTop: 15,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'white',
  },
  Landscapebutton: {
    alignItems: 'center',
    marginLeft: 110,
    marginRight: 110,
    marginBottom: 30,
  },
  LandscapetextSign: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
  },

  LandscapecenteredView: {
    justifyContent: 'center',
  },
  LandscapemodalView: {
    //margin: 20,
    marginHorizontal: '23%',
    backgroundColor: '#4F96BD',
    //backgroundColor: 'lightblue',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  LandscapemodalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 20,
    color: 'black',
    marginLeft: 10,
    marginRight: 10,
  },
  Landscapemodaltextresult: {
    //marginBottom: 15,
    textAlign: 'center',
    fontSize: 25,
    color: 'white',
    margin: 10,
  },
  Landscapemodalheading: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 25,
    color: 'white',
  },
  Landscapeflexbox7: {
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 10,
    marginBottom: 15,
  },
});
