import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  conatiner: {
    flex: 1,
    backgroundColor: 'white',
  },
  flexbox1: {
    flex: 0.45,
    //backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
  },
  circle: {
    width: 300,
    height: 300,
    borderRadius: 150,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'lightblue',
    borderWidth: 4,
    borderColor: '#4F96BD',
  },
  circletext: {
    textAlign: 'center',
    fontSize: 30,
    color: 'black',
    marginTop: 50,
  },
  bmitxet: {
    textAlign: 'center',
    fontSize: 55,
    fontWeight: 'bold',
    color: 'black',
  },
  activitytext: {
    textAlign: 'center',
    fontSize: 20,
    marginTop: 20,
    color: 'black',
    fontWeight: '500',
  },
  flexbox2: {
    flex: 0.07,
    //backgroundColor: 'yellow',
  },
  flexbox3: {
    flex: 0.2,
    //backgroundColor: 'gray',
    flexDirection: 'row',
  },
  button: {
    flex: 0.5,
    //backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 8,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#4F96BD',
  },
  image: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
  },
  text: {
    fontSize: 18,
    fontWeight: '500',
    //color: '#4F96BD',
    color: 'black',
    textAlign: 'center',
    marginTop: 10,
  },
  flexbox4: {
    flex: 0.12,
    //backgroundColor: 'yellow',
    flexDirection: 'row',
  },
  button1: {
    flex: 0.5,
    backgroundColor: 'lightblue',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 8,
    borderRadius: 7,
    borderWidth: 2,
    //borderColor: '#4F96BD',
    borderColor: 'black',
  },
  button2: {
    flex: 0.5,
    backgroundColor: 'lightblue',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 8,
    borderRadius: 7,
    borderWidth: 2,
    //borderColor: '#4F96BD',
    borderColor: 'black',
    opacity: 0.4,
  },
  modalView: {
    margin: 20,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'lightblue',
    borderRadius: 20,
    //padding: 35,
    paddingTop: 35,
    paddingBottom: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalheading: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 25,
    color: 'black',
  },
  signIn: {
    //width: '70%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'black',
    borderWidth: 1,
    marginTop: 15,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'white',
    marginLeft: 30,
    marginRight: 30,
  },
  textSign: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
  },
  text_footer: {
    color: 'black',
    fontSize: 18,
    marginTop: 25,
    marginRight: 280,
  },
  textInput: {
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    color: '#05375a',
    marginRight: 200,
  },
  flexbox5: {
    flexDirection: 'row',
    //backgroundColor: 'red',
    marginTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    paddingBottom: 5,
  },
  picker: {
    //flex: 1,
    justifyContent: 'center',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    paddingBottom: 5,
  },
  OEE: {
    textAlign: 'center',
    fontSize: 25,
    color: 'black',
    margin: 10,
  },
  flexbox6: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: 'white',
    marginTop: 30,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
  },

  Landscapeconatiner: {
    flex: 1,
    backgroundColor: 'white',
    flexDirection: 'row',
  },
  Landscapeflexbox1: {
    flex: 0.4,
    //backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  Landscapecircle: {
    width: 300,
    height: 300,
    borderRadius: 150,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'lightblue',
    borderWidth: 4,
    borderColor: '#4F96BD',
  },
  Landscapecircletext: {
    textAlign: 'center',
    fontSize: 30,
    color: 'black',
    marginTop: 50,
  },
  Landscapebmitxet: {
    textAlign: 'center',
    fontSize: 55,
    fontWeight: 'bold',
    color: 'black',
  },
  Landscapeactivitytext: {
    textAlign: 'center',
    fontSize: 20,
    //marginTop: 20,
    //marginBottom: 20,
    color: 'black',
    fontWeight: '500',
  },
  Landscapeflexbox2: {
    flex: 0.1,
    justifyContent: 'center',
    //backgroundColor: 'yellow',
    marginTop: 10,
    marginBottom: 10,
  },
  Landscapeflexbox3: {
    flex: 0.35,
    //backgroundColor: 'gray',
    flexDirection: 'row',
    marginLeft: 20,
    marginRight: 20,
  },
  Landscapebutton: {
    flex: 0.5,
    //backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 8,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#4F96BD',
  },
  Landscapeimage: {
    width: 55,
    height: 55,
    resizeMode: 'contain',
  },
  Landscapetext: {
    fontSize: 17,
    fontWeight: '500',
    //color: '#4F96BD',
    color: 'black',
    textAlign: 'center',
    marginTop: 10,
  },
  Landscapeflexbox4: {
    flex: 0.2,
    //backgroundColor: 'yellow',
    flexDirection: 'row',
  },
  Landscapebutton1: {
    flex: 0.5,
    backgroundColor: 'lightblue',
    alignItems: 'center',
    justifyContent: 'center',
    //margin: 8,
    marginTop: 8,
    marginBottom: 8,
    //marginLeft: 20,
    //marginRight: 20,
    marginHorizontal: '5%',
    borderRadius: 7,
    borderWidth: 2,
    //borderColor: '#4F96BD',
    borderColor: 'black',
  },
  Landscapebutton2: {
    flex: 0.5,
    backgroundColor: 'lightblue',
    alignItems: 'center',
    justifyContent: 'center',
    // margin: 8,
    marginTop: 8,
    marginBottom: 8,
    marginLeft: 17,
    marginRight: 17,
    borderRadius: 7,
    borderWidth: 2,
    //borderColor: '#4F96BD',
    borderColor: 'black',
    opacity: 0.4,
  },
  LandscapemodalView: {
    //margin: 20,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'lightblue',
    borderRadius: 20,
    marginHorizontal: '25%',
    //padding: 35,
    paddingTop: 35,
    paddingBottom: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  Landscapemodalheading: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 25,
    color: 'black',
  },
  LandscapesignIn: {
    //width: '70%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'black',
    borderWidth: 1,
    marginTop: 15,
    //backgroundColor: '#4F96BD',
    backgroundColor: 'white',
    marginLeft: 30,
    marginRight: 30,
  },
  LandscapetextSign: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
  },
  Landscapetext_footer: {
    color: 'black',
    fontSize: 18,
    marginTop: 25,
    marginRight: 280,
  },
  LandscapetextInput: {
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    color: '#05375a',
    marginRight: 200,
  },
  Landscapeflexbox5: {
    flexDirection: 'row',
    //backgroundColor: 'red',
    marginTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    paddingBottom: 5,
  },
  Landscapepicker: {
    //flex: 1,
    justifyContent: 'center',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    paddingBottom: 5,
  },
  LandscapeOEE: {
    textAlign: 'center',
    fontSize: 25,
    color: 'black',
    margin: 10,
  },
  Landscapeflexbox6: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: 'white',
    marginTop: 30,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 20,
  },
});
