import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  conatiner: {
    flex: 1,
    backgroundColor: 'lightblue',
    backgroundColor: 'white',
  },
  flexbox1: {
    flex: 0.2,
    //backgroundColor: 'lightblue',
    justifyContent: 'center',
  },
  heading: {
    textAlign: 'center',
    fontSize: 25,
    fontWeight: 'bold',
    color: 'black',
  },
  flexbox2: {
    flex: 0.5,
    //backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backgroundgif: {
    height: 200,
    width: 200,
  },
  flexbox3: {
    flex: 0.1,
    flexDirection: 'row',
  },
  flexbox4: {
    flex: 0.5,
    //backgroundColor: 'blue',
    justifyContent: 'center',
  },
  exercisename: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
    fontWeight: 'bold',
    borderWidth: 1,
    borderRadius: 7,
    marginLeft: 20,
    marginRight: 5,
    backgroundColor: 'lightblue',
    marginBottom: 20,
  },
  flexbox5: {
    flex: 0.5,
    //backgroundColor: 'lightblue',
    justifyContent: 'center',
  },
  exerciseno: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
    fontWeight: 'bold',
    borderWidth: 1,
    borderRadius: 7,
    marginRight: 20,
    marginLeft: 5,
    backgroundColor: 'lightblue',
    marginBottom: 20,
  },

  Landscapeconatiner: {
    flex: 1,
    //backgroundColor: 'lightblue',
    backgroundColor: 'white',
  },
  Landscapeflexbox1: {
    flex: 0.2,
    //backgroundColor: 'lightblue',
    justifyContent: 'center',
  },
  Landscapeheading: {
    textAlign: 'center',
    fontSize: 25,
    fontWeight: 'bold',
    color: 'black',
  },
  Landscapeflexbox2: {
    flex: 0.5,
    //backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: '25%',
  },
  Landscapebackgroundgif: {
    height: 200,
    width: 200,
  },
  Landscapeflexbox3: {
    flex: 0.5,
    flexDirection: 'row',
  },
  Landscapeflexbox4: {
    flex: 0.5,
    //backgroundColor: 'blue',
    justifyContent: 'center',
  },
  Landscapeexercisename: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
    fontWeight: 'bold',
    borderWidth: 1,
    borderRadius: 7,
    marginLeft: 20,
    marginRight: 5,
    backgroundColor: 'lightblue',
    //marginBottom: 20,
  },
  Landscapeflexbox5: {
    flex: 0.5,
    //backgroundColor: 'lightblue',
    justifyContent: 'center',
  },
  Landscapeexerciseno: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
    fontWeight: 'bold',
    borderWidth: 1,
    borderRadius: 7,
    marginRight: 20,
    marginLeft: 5,
    backgroundColor: 'lightblue',
    //marginBottom: 20,
  },
});
