import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  conatiner: {
    flex: 1,
    //backgroundColor: 'lightblue',
    backgroundColor: 'white',
  },
  flexbox3: {
    flex: 0.35,
    //backgroundColor: 'gray',
    flexDirection: 'row',
  },
  button: {
    flex: 0.5,
    //backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#4F96BD',
  },
  image: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    marginTop: 5,
  },
  text: {
    fontSize: 18,
    fontWeight: '500',
    //color: '#4F96BD',
    color: 'black',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  activitytext: {
    textAlign: 'center',
    fontSize: 20,
    //marginTop: 20,
    color: 'black',
    fontWeight: '500',
    marginTop: 15,
    marginBottom: 15,
  },
  flexbox2: {
    flex: 0.1,
    //backgroundColor: 'lightblue',
    justifyContent: 'center',
  },
  flexbox4: {
    flex: 0.1,
    //backgroundColor: 'yellow',
    justifyContent: 'center',
  },
  text1: {
    textAlign: 'center',
    fontSize: 15,
    color: 'black',
    marginTop: 15,
    marginBottom: 15,
  },
  flexbox5: {
    flex: 0.1,
    //backgroundColor: 'pink',
    justifyContent: 'center',
    marginLeft: 55,
    marginRight: 55,
  },
  text2: {
    textAlign: 'center',
    fontSize: 25,
    color: 'black',
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 15,
    marginBottom: 10,
  },
  flexbox6: {
    flex: 0.1,
    justifyContent: 'center',
  },
  text3: {
    textAlign: 'center',
    fontSize: 15,
    color: 'black',
    marginTop: 10,
    marginBottom: 10,
  },
  text4: {
    textAlign: 'right',
    fontSize: 15,
    color: 'black',
    marginRight: 70,
    marginTop: 10,
    marginBottom: 10,
  },
  flexbox8: {
    flex: 0.15,
    flexDirection: 'row',
  },
  box: {
    flex: 0.1,
    backgroundColor: '#F44336',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 13,
    marginBottom: 13,
    borderRadius: 5,
  },
  box1: {
    flex: 0.1,
    backgroundColor: '#2196F3',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 13,
    marginBottom: 13,
    borderRadius: 5,
  },
  box2: {
    flex: 0.1,
    backgroundColor: '#FF9800',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 13,
    marginBottom: 13,
    borderRadius: 5,
  },
  flexbox9: {
    flex: 0.4,
    justifyContent: 'center',
  },
  text5: {
    fontSize: 20,
    color: 'black',
    marginTop: 15,
    marginBottom: 15,
  },
  text6: {
    textAlign: 'center',
    fontSize: 20,
    color: 'black',
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 15,
    marginBottom: 15,
  },

  Landscapeconatiner: {
    flex: 1,
    //backgroundColor: 'lightblue',
    backgroundColor: 'white',
  },
  Landscapeflexbox3: {
    flex: 0.35,
    //backgroundColor: 'gray',
    flexDirection: 'row',
  },
  Landscapebutton: {
    flex: 0.5,
    //backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 10,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#4F96BD',
    //marginLeft: 90,
    //marginRight: 90,
    marginTop: 10,
    marginBottom: 10,
  },
  Landscapeimage: {
    width: 70,
    height: 70,
    resizeMode: 'contain',
    marginTop: 10,
    marginBottom: 10,
  },
  Landscapetext: {
    fontSize: 18,
    fontWeight: '500',
    //color: '#4F96BD',
    color: 'black',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  Landscapeactivitytext: {
    textAlign: 'center',
    fontSize: 20,
    //marginTop: 20,
    color: 'black',
    fontWeight: '500',
    marginTop: 15,
    marginBottom: 15,
  },
  Landscapeflexbox2: {
    flex: 0.1,
    //backgroundColor: 'lightblue',
    justifyContent: 'center',
  },
  Landscapeflexbox4: {
    flex: 0.1,
    //backgroundColor: 'yellow',
    justifyContent: 'center',
  },
  Landscapetext1: {
    textAlign: 'center',
    fontSize: 15,
    color: 'black',
    marginTop: 15,
    marginBottom: 15,
  },
  Landscapeflexbox5: {
    flex: 0.1,
    //backgroundColor: 'pink',
    justifyContent: 'center',
    marginLeft: 250,
    marginRight: 250,
  },
  Landscapetext2: {
    textAlign: 'center',
    fontSize: 25,
    color: 'black',
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 15,
    marginBottom: 10,
  },
  Landscapeflexbox6: {
    flex: 0.1,
    justifyContent: 'center',
  },
  Landscapetext3: {
    textAlign: 'center',
    fontSize: 15,
    color: 'black',
    marginTop: 10,
    marginBottom: 10,
  },
  Landscapetext4: {
    textAlign: 'right',
    fontSize: 15,
    color: 'black',
    //marginRight: 200,
    marginHorizontal: '35%',
    marginTop: 10,
    marginBottom: 10,
  },
  Landscapeflexbox8: {
    flex: 0.15,
    flexDirection: 'row',
    marginHorizontal: '27%',
  },
  Landscapebox: {
    flex: 0.1,
    backgroundColor: '#F44336',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 13,
    marginBottom: 13,
    borderRadius: 5,
  },
  Landscapebox1: {
    flex: 0.1,
    backgroundColor: '#2196F3',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 13,
    marginBottom: 13,
    borderRadius: 5,
  },
  Landscapebox2: {
    flex: 0.1,
    backgroundColor: '#FF9800',
    marginLeft: 20,
    marginRight: 20,
    marginTop: 13,
    marginBottom: 13,
    borderRadius: 5,
  },
  Landscapeflexbox9: {
    flex: 0.4,
    justifyContent: 'center',
  },
  Landscapetext5: {
    fontSize: 20,
    color: 'black',
    marginTop: 15,
    marginBottom: 15,
  },
  Landscapetext6: {
    textAlign: 'center',
    fontSize: 20,
    color: 'black',
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 15,
    marginBottom: 15,
  },
});
