import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    //backgroundColor: 'lightblue',
  },
  button1: {
    flex: 0.1,
    backgroundColor: 'lightblue',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 8,
    borderRadius: 7,
    borderWidth: 2,
    //borderColor: '#4F96BD',
    borderColor: 'black',
  },
  button2: {
    flex: 0.1,
    backgroundColor: 'lightblue',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 8,
    borderRadius: 7,
    borderWidth: 2,
    //borderColor: '#4F96BD',
    borderColor: 'black',
    opacity: 0.4,
  },
  text: {
    fontSize: 18,
    fontWeight: '500',
    //color: '#4F96BD',
    color: 'black',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  mainflex1: {
    flex: 0.4,
  },
  flexbox1: {
    flex: 0.1,
    //backgroundColor: 'gray',
    justifyContent: 'center',
    marginTop: 10,
    //marginBottom: 10,
  },
  heading: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
    marginTop: 10,
    marginBottom: 10,
  },
  flexbox2: {
    flex: 0.28,
    //backgroundColor: 'pink',
    justifyContent: 'center',
    alignItems: 'center',
  },
  outcircle: {
    marginTop: 8,
    marginBottom: 8,
  },
  circletext: {
    fontSize: 37,
    color: 'black',
    textAlign: 'center',
  },
  circletext2: {
    fontSize: 15,
    textAlign: 'center',
    color: 'black',
  },
  flexbox3: {
    flex: 0.07,
    flexDirection: 'row',
  },
  inputtext: {
    flex: 0.5,
    marginTop: 6,
    marginLeft: 28,
    justifyContent: 'center',
    alignItems: 'center',
    //backgroundColor: 'yellow',
    paddingLeft: 10,
    color: '#05375a',
    borderWidth: 1,
    borderColor: '#666666',
    borderRadius: 10,
  },
  remainingtext: {
    flex: 0.5,
    //backgroundColor: 'green',
    justifyContent: 'center',
    textAlign: 'center',
    marginRight: 28,
    fontSize: 20,
    marginTop: 8,
    color: 'black',
  },
  flexbox4: {
    flex: 0.05,
    flexDirection: 'row',
  },
  text1: {
    flex: 0.5,
    //backgroundColor: 'pink',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: 15,
    color: 'black',
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 20,
  },
  flexbox5: {
    marginLeft: 20,
    marginRight: 20,
    marginTop: 45,
  },

  Landscapecontainer: {
    flex: 1,
    //backgroundColor: 'lightblue',
  },
  Landscapebutton1: {
    //flex: 0.1,
    backgroundColor: 'lightblue',
    alignItems: 'center',
    justifyContent: 'center',
    //margin: 8,
    borderRadius: 7,
    borderWidth: 2,
    //borderColor: '#4F96BD',
    borderColor: 'black',
  },
  Landscapebutton2: {
    //flex: 0.1,
    backgroundColor: 'lightblue',
    alignItems: 'center',
    justifyContent: 'center',
    //margin: 8,
    borderRadius: 7,
    borderWidth: 2,
    //borderColor: '#4F96BD',
    borderColor: 'black',
    opacity: 0.4,
  },
  Landscapetext: {
    fontSize: 18,
    fontWeight: '500',
    //color: '#4F96BD',
    color: 'black',
    textAlign: 'center',
    //marginTop: 10,
    //marginBottom: 10,
  },
  Landscapemainflex1: {
    flex: 0.8,
    flexDirection: 'row',
    //backgroundColor: 'lightblue',
  },
  Landscapeflexbox1: {
    flex: 0.1,
    //backgroundColor: 'gray',
    justifyContent: 'center',
    //marginTop: 10,
    //marginBottom: 10,
  },
  Landscapeheading: {
    fontSize: 20,
    textAlign: 'center',
    color: 'black',
    //marginTop: 10,
    //marginBottom: 10,
  },
  Landscapeflexbox2: {
    flex: 0.7,
    //backgroundColor: 'pink',
    justifyContent: 'center',
    alignItems: 'center',
  },
  Landscapeoutcircle: {
    marginTop: 8,
    marginBottom: 8,
  },
  Landscapecircletext: {
    fontSize: 32,
    color: 'black',
    textAlign: 'center',
  },
  Landscapecircletext2: {
    fontSize: 13,
    textAlign: 'center',
    color: 'black',
  },
  Landscapeflexbox3: {
    flex: 0.2,
    //backgroundColor: 'yellow',
    flexDirection: 'row',
  },
  Landscapeinputtext: {
    flex: 0.5,
    //marginTop: 6,
    //marginLeft: 30,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 20,
    //backgroundColor: 'yellow',
    //paddingLeft: 10,
    color: '#05375a',
    textAlign: 'center',
    borderWidth: 1,
    borderColor: '#666666',
    borderRadius: 10,
    marginLeft: 10,
  },
  Landscaperemainingtext: {
    flex: 0.5,
    //backgroundColor: 'green',
    justifyContent: 'center',
    textAlign: 'center',
    //marginRight: 28,
    fontSize: 20,
    marginTop: 8,
    marginBottom: 8,
    color: 'black',
  },
  Landscapeflexbox4: {
    flex: 0.2,
    //backgroundColor: 'blue',
    flexDirection: 'row',
  },
  Landscapetext1: {
    flex: 0.5,
    //backgroundColor: 'pink',
    justifyContent: 'center',
    textAlign: 'center',
    fontSize: 15,
    color: 'black',
    marginTop: 10,
    marginBottom: 10,
  },
  Landscapeflexbox5: {
    flex: 0.1,
    //backgroundColor: 'red',
    marginHorizontal: '40%',
    //marginLeft: 20,
    //marginRight: 20,
    //marginTop: 45,
  },
});
